// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	api "github.com/vishen/go-chromecast/cast/proto"

	mock "github.com/stretchr/testify/mock"
)

// CastMessageFunc is an autogenerated mock type for the CastMessageFunc type
type CastMessageFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *CastMessageFunc) Execute(_a0 *api.CastMessage) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewCastMessageFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewCastMessageFunc creates a new instance of CastMessageFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCastMessageFunc(t mockConstructorTestingTNewCastMessageFunc) *CastMessageFunc {
	mock := &CastMessageFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
