// Code generated by mockery v2.8.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	application "github.com/vishen/go-chromecast/application"
)

// ApplicationOption is an autogenerated mock type for the ApplicationOption type
type ApplicationOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ApplicationOption) Execute(_a0 application.Application) {
	_m.Called(_a0)
}
