// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Payload is an autogenerated mock type for the Payload type
type Payload struct {
	mock.Mock
}

// SetRequestId provides a mock function with given fields: id
func (_m *Payload) SetRequestId(id int) {
	_m.Called(id)
}

// NewPayload creates a new instance of Payload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *Payload {
	mock := &Payload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
