// Code generated by mockery v2.8.0. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Payload is an autogenerated mock type for the Payload type
type Payload struct {
	mock.Mock
}

// SetRequestId provides a mock function with given fields: id
func (_m *Payload) SetRequestId(id int) {
	_m.Called(id)
}
